In [32]:
from sklearn.model_selection import train_test_split
import pandas as pd

In [33]:
data = pd.read_csv('./hfi_cc_2018.csv')
data.dropna(subset = ['hf_score'], inplace=True)

In [34]:
train, test = train_test_split(data, train_size = .75, random_state = 0)

In [35]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1033 entries, 542 to 697
Columns: 123 entries, year to hf_quartile
dtypes: float64(119), int64(1), object(3)
memory usage: 1000.7+ KB

In [36]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 345 entries, 1062 to 331
Columns: 123 entries, year to hf_quartile
dtypes: float64(119), int64(1), object(3)
memory usage: 334.2+ KB

In [37]:
train = train.reset_index(drop = True)

In [38]:
train.head()

,year,ISO_code,countries,region,pf_rol_procedural,pf_rol_civil,pf_rol_criminal,pf_rol,pf_ss_homicide,pf_ss_disappearances_disap,...,ef_regulation_business_bribes,ef_regulation_business_licensing,ef_regulation_business_compliance,ef_regulation_business,ef_regulation,ef_score,ef_rank,hf_score,hf_rank,hf_quartile
0,2013,GRC,Greece,Eastern Europe,6.700000,6.100000,4.600000,5.793651,9.459426,10.0,...,4.368423,8.895988,7.836600,6.511455,6.615249,6.88,82.0,7.486946,50.0,2.0
1,2012,COG,"Congo, Rep. Of",Sub-Saharan Africa,NaN,NaN,NaN,3.554800,6.053027,10.0,...,NaN,6.703546,3.251985,3.979304,5.521279,4.39,152.0,5.334761,143.0,4.0
2,2009,FJI,Fiji,Oceania,NaN,NaN,NaN,4.343008,8.638445,10.0,...,NaN,8.631834,8.172880,8.360649,8.979383,7.08,59.0,7.318471,56.0,2.0
3,2009,IRL,Ireland,Western Europe,NaN,NaN,NaN,7.893729,9.509639,10.0,...,8.260776,7.683106,9.148091,7.010010,7.858009,7.76,12.0,8.402759,11.0,1.0
4,2011,ARE,United Arab Emirates,Middle East & North Africa,6.066667,6.037091,7.486491,6.500000,9.764773,10.0,...,8.618148,9.983350,9.865488,8.884073,8.576617,7.69,17.0,6.264678,120.0,4.0

In [39]:
train.drop(columns = ['hf_rank', 'hf_quartile'], axis = 1, inplace = True)

In [40]:
train.dropna(subset = ['hf_score'], inplace=True)

In [41]:
train.to_csv('train.csv')

In [42]:
test = test.reset_index(drop = True)

In [43]:
test.head()

,year,ISO_code,countries,region,pf_rol_procedural,pf_rol_civil,pf_rol_criminal,pf_rol,pf_ss_homicide,pf_ss_disappearances_disap,...,ef_regulation_business_bribes,ef_regulation_business_licensing,ef_regulation_business_compliance,ef_regulation_business,ef_regulation,ef_score,ef_rank,hf_score,hf_rank,hf_quartile
0,2010,MDG,Madagascar,Sub-Saharan Africa,4.300000,5.349745,4.949092,4.900000,6.329103,5.0,...,3.035905,7.349900,7.746925,5.841701,6.258045,6.41,104.0,6.616477,103.0,3.0
1,2012,BEL,Belgium,Western Europe,8.500000,6.900000,6.700000,7.360317,9.260165,10.0,...,7.306827,7.330529,8.206508,7.336116,8.090983,7.35,42.0,8.191891,23.0,1.0
2,2013,MMR,Myanmar,South Asia,2.100000,3.900000,3.200000,3.087302,9.037478,5.0,...,2.163515,8.815891,8.268159,4.413571,5.563482,5.35,146.0,5.190548,150.0,4.0
3,2016,CHL,Chile,Latin America & the Caribbean,7.706122,6.291439,5.550751,6.516104,8.614887,10.0,...,5.964517,8.747894,6.738086,7.176759,7.098290,7.80,15.0,8.008018,32.0,1.0
4,2015,MLT,Malta,Western Europe,NaN,NaN,NaN,7.086754,9.625833,10.0,...,4.659129,8.191041,8.441904,6.552776,8.097235,7.72,18.0,8.380704,18.0,1.0

In [44]:
test.dropna(subset = ['hf_score'], inplace=True)

In [45]:
solutions = pd.DataFrame({'Id':test.index,
                          'hf_score': test.hf_score})

In [49]:
sample_submission = pd.DataFrame({'Id':test.index,
                          'hf_score': test.hf_score.mean()})

In [50]:
sample_submission.to_csv('sample_submission.csv', index = False)

In [48]:
solutions.to_csv('solutions.csv', index = False)

In [18]:
test.drop(columns = ['hf_score', 'hf_rank', 'hf_quartile'], axis = 1, inplace=True)

In [19]:
test.to_csv('test.csv')

In [28]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 345 entries, 0 to 344
Columns: 120 entries, year to ef_rank
dtypes: float64(116), int64(1), object(3)
memory usage: 326.1+ KB

In [29]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1033 entries, 0 to 1032
Columns: 121 entries, year to hf_score
dtypes: float64(117), int64(1), object(3)
memory usage: 984.6+ KB

In [21]:
train.head()

,year,ISO_code,countries,region,pf_rol_procedural,pf_rol_civil,pf_rol_criminal,pf_rol,pf_ss_homicide,pf_ss_disappearances_disap,...,ef_regulation_business_bureaucracy,ef_regulation_business_start,ef_regulation_business_bribes,ef_regulation_business_licensing,ef_regulation_business_compliance,ef_regulation_business,ef_regulation,ef_score,ef_rank,hf_score
0,2013,GRC,Greece,Eastern Europe,6.700000,6.100000,4.600000,5.793651,9.459426,10.0,...,6.000000,9.560675,4.368423,8.895988,7.836600,6.511455,6.615249,6.88,82.0,7.486946
1,2012,COG,"Congo, Rep. Of",Sub-Saharan Africa,NaN,NaN,NaN,3.554800,6.053027,10.0,...,0.000000,5.961685,NaN,6.703546,3.251985,3.979304,5.521279,4.39,152.0,5.334761
2,2009,FJI,Fiji,Oceania,NaN,NaN,NaN,4.343008,8.638445,10.0,...,NaN,8.277233,NaN,8.631834,8.172880,8.360649,8.979383,7.08,59.0,7.318471
3,2009,IRL,Ireland,Western Europe,NaN,NaN,NaN,7.893729,9.509639,10.0,...,3.952381,9.579583,8.260776,7.683106,9.148091,7.010010,7.858009,7.76,12.0,8.402759
4,2011,ARE,United Arab Emirates,Middle East & North Africa,6.066667,6.037091,7.486491,6.500000,9.764773,10.0,...,8.787879,9.680841,8.618148,9.983350,9.865488,8.884073,8.576617,7.69,17.0,6.264678

In [22]:
corr = train.corr()[['hf_score']].sort_values('hf_score',ascending = False)

In [23]:
corr[abs(corr.hf_score) >0.5]

                                    hf_score
hf_score                            1.000000
pf_score                            0.940239
pf_rol_procedural                   0.868228
ef_score                            0.852416
pf_rol                              0.815282
ef_legal                            0.807159
ef_trade                            0.794442
pf_expression_control               0.754154
pf_expression_influence             0.733544
pf_expression                       0.723847
pf_movement                         0.720264
ef_money                            0.720184
pf_ss                               0.719594
pf_rol_criminal                     0.719137
pf_rol_civil                        0.714543
ef_trade_regulatory                 0.711040
ef_legal_military                   0.708141
pf_ss_disappearances_organized      0.691557
ef_trade_movement                   0.684129
pf_ss_women_inheritance_daughters   0.677153
pf_identity                         0.675037
pf_association                      0.669752
ef_trade_regulatory_compliance      0.666451
ef_regulation_business_bureaucracy  0.658032
ef_regulation                       0.655865
pf_ss_women                         0.651628
pf_ss_women_inheritance             0.651333
pf_ss_women_inheritance_widows      0.649347
ef_regulation_business              0.633453
pf_association_prof_operate         0.632551
...                                      ...
ef_regulation_business_bribes       0.607307
pf_association_political            0.589503
ef_trade_movement_foreign           0.589079
ef_legal_police                     0.586542
pf_expression_newspapers            0.585769
pf_association_prof                 0.584891
pf_association_sport                0.583657
pf_movement_domestic                0.576601
ef_legal_integrity                  0.575663
ef_trade_tariffs_mean               0.575157
ef_legal_judicial                   0.571770
ef_money_sd                         0.567121
pf_movement_women                   0.567074
pf_association_political_operate    0.567005
pf_association_sport_operate        0.566173
ef_trade_regulatory_nontariff       0.562978
pf_identity_parental_divorce        0.559902
ef_regulation_credit                0.551472
pf_movement_foreign                 0.547251
pf_identity_sex                     0.537477
ef_regulation_credit_ownership      0.536126
ef_government_enterprises           0.524033
ef_trade_movement_visit             0.520167
pf_religion_estop                   0.515421
pf_identity_sex_male                0.506686
pf_identity_divorce                 0.504082
pf_religion_estop_operate           0.503224
ef_government_transfers            -0.572464
ef_rank                            -0.858335
pf_rank                            -0.930971

[67 rows x 1 columns]

In [24]:
train.head()

,year,ISO_code,countries,region,pf_rol_procedural,pf_rol_civil,pf_rol_criminal,pf_rol,pf_ss_homicide,pf_ss_disappearances_disap,...,ef_regulation_business_bureaucracy,ef_regulation_business_start,ef_regulation_business_bribes,ef_regulation_business_licensing,ef_regulation_business_compliance,ef_regulation_business,ef_regulation,ef_score,ef_rank,hf_score
0,2013,GRC,Greece,Eastern Europe,6.700000,6.100000,4.600000,5.793651,9.459426,10.0,...,6.000000,9.560675,4.368423,8.895988,7.836600,6.511455,6.615249,6.88,82.0,7.486946
1,2012,COG,"Congo, Rep. Of",Sub-Saharan Africa,NaN,NaN,NaN,3.554800,6.053027,10.0,...,0.000000,5.961685,NaN,6.703546,3.251985,3.979304,5.521279,4.39,152.0,5.334761
2,2009,FJI,Fiji,Oceania,NaN,NaN,NaN,4.343008,8.638445,10.0,...,NaN,8.277233,NaN,8.631834,8.172880,8.360649,8.979383,7.08,59.0,7.318471
3,2009,IRL,Ireland,Western Europe,NaN,NaN,NaN,7.893729,9.509639,10.0,...,3.952381,9.579583,8.260776,7.683106,9.148091,7.010010,7.858009,7.76,12.0,8.402759
4,2011,ARE,United Arab Emirates,Middle East & North Africa,6.066667,6.037091,7.486491,6.500000,9.764773,10.0,...,8.787879,9.680841,8.618148,9.983350,9.865488,8.884073,8.576617,7.69,17.0,6.264678

In [25]:
test.head()

,year,ISO_code,countries,region,pf_rol_procedural,pf_rol_civil,pf_rol_criminal,pf_rol,pf_ss_homicide,pf_ss_disappearances_disap,...,ef_regulation_business_adm,ef_regulation_business_bureaucracy,ef_regulation_business_start,ef_regulation_business_bribes,ef_regulation_business_licensing,ef_regulation_business_compliance,ef_regulation_business,ef_regulation,ef_score,ef_rank
0,2010,MDG,Madagascar,Sub-Saharan Africa,4.300000,5.349745,4.949092,4.900000,6.329103,5.0,...,3.209803,4.090909,9.616764,3.035905,7.349900,7.746925,5.841701,6.258045,6.41,104.0
1,2012,BEL,Belgium,Western Europe,8.500000,6.900000,6.700000,7.360317,9.260165,10.0,...,2.748521,8.666667,9.757642,7.306827,7.330529,8.206508,7.336116,8.090983,7.35,42.0
2,2013,MMR,Myanmar,South Asia,2.100000,3.900000,3.200000,3.087302,9.037478,5.0,...,3.176697,1.333333,2.723830,2.163515,8.815891,8.268159,4.413571,5.563482,5.35,146.0
3,2016,CHL,Chile,Latin America & the Caribbean,7.706122,6.291439,5.550751,6.516104,8.614887,10.0,...,4.039881,7.777778,9.792396,5.964517,8.747894,6.738086,7.176759,7.098290,7.80,15.0
4,2015,MLT,Malta,Western Europe,NaN,NaN,NaN,7.086754,9.625833,10.0,...,4.101592,4.888889,9.034103,4.659129,8.191041,8.441904,6.552776,8.097235,7.72,18.0

In [26]:
test.head()

,year,ISO_code,countries,region,pf_rol_procedural,pf_rol_civil,pf_rol_criminal,pf_rol,pf_ss_homicide,pf_ss_disappearances_disap,...,ef_regulation_business_adm,ef_regulation_business_bureaucracy,ef_regulation_business_start,ef_regulation_business_bribes,ef_regulation_business_licensing,ef_regulation_business_compliance,ef_regulation_business,ef_regulation,ef_score,ef_rank
0,2010,MDG,Madagascar,Sub-Saharan Africa,4.300000,5.349745,4.949092,4.900000,6.329103,5.0,...,3.209803,4.090909,9.616764,3.035905,7.349900,7.746925,5.841701,6.258045,6.41,104.0
1,2012,BEL,Belgium,Western Europe,8.500000,6.900000,6.700000,7.360317,9.260165,10.0,...,2.748521,8.666667,9.757642,7.306827,7.330529,8.206508,7.336116,8.090983,7.35,42.0
2,2013,MMR,Myanmar,South Asia,2.100000,3.900000,3.200000,3.087302,9.037478,5.0,...,3.176697,1.333333,2.723830,2.163515,8.815891,8.268159,4.413571,5.563482,5.35,146.0
3,2016,CHL,Chile,Latin America & the Caribbean,7.706122,6.291439,5.550751,6.516104,8.614887,10.0,...,4.039881,7.777778,9.792396,5.964517,8.747894,6.738086,7.176759,7.098290,7.80,15.0
4,2015,MLT,Malta,Western Europe,NaN,NaN,NaN,7.086754,9.625833,10.0,...,4.101592,4.888889,9.034103,4.659129,8.191041,8.441904,6.552776,8.097235,7.72,18.0

In [27]:
sample_submission

      Id  hf_score
0      0  6.927536
1      1  6.927536
2      2  6.927536
3      3  6.927536
4      4  6.927536
5      5  6.927536
6      6  6.927536
7      7  6.927536
8      8  6.927536
9      9  6.927536
10    10  6.927536
11    11  6.927536
12    12  6.927536
13    13  6.927536
14    14  6.927536
15    15  6.927536
16    16  6.927536
17    17  6.927536
18    18  6.927536
19    19  6.927536
20    20  6.927536
21    21  6.927536
22    22  6.927536
23    23  6.927536
24    24  6.927536
25    25  6.927536
26    26  6.927536
27    27  6.927536
28    28  6.927536
29    29  6.927536
..   ...       ...
315  315  6.927536
316  316  6.927536
317  317  6.927536
318  318  6.927536
319  319  6.927536
320  320  6.927536
321  321  6.927536
322  322  6.927536
323  323  6.927536
324  324  6.927536
325  325  6.927536
326  326  6.927536
327  327  6.927536
328  328  6.927536
329  329  6.927536
330  330  6.927536
331  331  6.927536
332  332  6.927536
333  333  6.927536
334  334  6.927536
335  335  6.927536
336  336  6.927536
337  337  6.927536
338  338  6.927536
339  339  6.927536
340  340  6.927536
341  341  6.927536
342  342  6.927536
343  343  6.927536
344  344  6.927536

[345 rows x 2 columns]